[package]
name = "mathematics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
nalgebra = { version = "0.32.3", features = ["rand"] }
num-traits = "0.2"
